pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: 3.7
    architecture: x64
- script: |
    git push -f "https://$DEPLOYMENT_USERNAME:$DEPLOYMENT_PASSWORD@$DEPLOYMENT_URL" HEAD:master
  env:
    DEPLOYMENT_URL: $(DEPLOYMENT_URL)
    DEPLOYMENT_USERNAME: $(DEPLOYMENT_USERNAME)
    DEPLOYMENT_PASSWORD: $(DEPLOYMENT_PASSWORD)
  displayName: 'LocalGit Deploy'
